let RUF_players = [
    {
        name: 'Jenry',
        handler: false,
        female: false,
        speed: 5,
        height: 174,
    },
    {
        name: 'Lucy',
        handler: true,
        female: false,
        speed: 5,
        height: 174,
    },
    {
        name: 'Cardu',
        handler: true,
        female: false,
        speed: 5,
    },
    {
        name: 'Uli',
        handler: true,
        female: false,
    },
    {
        name: 'Scooby',
        handler: true,
        female: false,
    },
    {
        name: 'Rodri',
        handler: true,
        female: false,
    },
    {
        name: 'Orne',
        handler: true,
        female: true,
    },
    {
        name: 'Negra',
        handler: true,
        female: true,
    },
    {
        name: 'Dani',
        handler: false,
        female: true,
    },
    {
        name: 'Lu',
        handler: false,
        female: true,
    },
    {
        name: 'Bian',
        handler: false,
        female: true,
    },
    {
        name: 'Oli',
        handler: false,
        female: true,
    },
    { name: 'Gino', handler: false, female: false, },
    { name: 'Juancho', handler: true, female: false, },
    { name: 'Vigny', handler: true, female: false, },
    { name: 'Emi', handler: false, female: false, },
    { name: 'Gaby', handler: true, female: false, },
    { name: 'Gonza', handler: true, female: false, },
    { name: 'Grillo', handler: false, female: false, },
    { name: 'Nacho', handler: false, female: false, },
    { name: 'Jose', handler: false, female: true, },
    { name: 'Juanma', handler: false, female: false, },
    { name: 'Kervey', handler: true, female: false, },
    { name: 'Lean', handler: true, female: false, },
    { name: 'Leon', handler: false, female: false, },
    { name: 'Maxi', handler: false, female: false, },
    { name: 'Pyro', handler: false, female: false, },
    { name: 'Tano', handler: true, female: false, },
    { name: 'Milo', handler: true, female: false, },
    { name: 'Orma', handler: false, female: false, },
    { name: 'Gio', handler: false, female: false, },
    { name: 'Pablo', handler: false, female: false, },
    { name: 'Toby', handler: false, female: false, },
    { name: 'Tomy', handler: false, female: false, },
    { name: 'Javi', handler: true, female: false, },
{ name: 'Castor', handler: false, female: false, },

];
